export const defaultPermissions = [
  // 系统管理
  { parent_id: 0, perm_name: '系统管理', perm_code: 'system', type: 'menu', icon: 'SettingOutlined', path: 'system', sort_order: 8 },
  { parent_id: 0, parent_code: 'system', perm_name: '用户管理', perm_code: 'system:user', type: 'menu', icon: 'TeamOutlined', path: '/system/users', sort_order: 1 },
  { parent_id: 0, parent_code: 'system', perm_name: '角色权限', perm_code: 'system:role', type: 'menu', icon: 'SafetyCertificateOutlined', path: '/system/roles', sort_order: 2 },
  { parent_id: 0, parent_code: 'system', perm_name: '菜单管理', perm_code: 'system:menu', type: 'menu', icon: 'MenuOutlined', path: '/system/menus', sort_order: 3 },
  { parent_id: 0, parent_code: 'system', perm_name: '数据字典', perm_code: 'system:dict', type: 'menu', icon: 'DatabaseOutlined', path: '/system/dictionary', sort_order: 4 },
  { parent_id: 0, parent_code: 'system', perm_name: '系统配置', perm_code: 'system:config', type: 'menu', icon: 'ControlOutlined', path: '/system/config', sort_order: 5 },
  { parent_id: 0, parent_code: 'system', perm_name: '操作日志', perm_code: 'system:log', type: 'menu', icon: 'FileTextOutlined', path: '/system/logs', sort_order: 6 },
  { parent_id: 0, parent_code: 'system', perm_name: '系统日志', perm_code: 'system:system-log', type: 'menu', icon: 'BugOutlined', path: '/system/system-logs', sort_order: 8 },
  // 基础数据
  { parent_id: 0, perm_name: '基础数据', perm_code: 'basic', type: 'menu', icon: 'ProfileOutlined', path: 'basic', sort_order: 4 },
  { parent_id: 0, parent_code: 'basic', perm_name: '料品档案', perm_code: 'basic:material', type: 'menu', icon: 'ProfileOutlined', path: '/basic/materials', sort_order: 1 },
  { parent_id: 0, parent_code: 'basic', perm_name: '客户档案', perm_code: 'basic:customer', type: 'menu', icon: 'TeamOutlined', path: '/basic/customers', sort_order: 2 },
  { parent_id: 0, parent_code: 'basic', perm_name: '供应商档案', perm_code: 'basic:supplier', type: 'menu', icon: 'ShopOutlined', path: '/basic/suppliers', sort_order: 3 },
  { parent_id: 0, parent_code: 'basic', perm_name: '产线档案', perm_code: 'basic:line', type: 'menu', icon: 'DeploymentUnitOutlined', path: '/basic/lines', sort_order: 4 },
  { parent_id: 0, parent_code: 'basic', perm_name: '工序档案', perm_code: 'basic:process', type: 'menu', icon: 'DeploymentUnitOutlined', path: '/basic/processes', sort_order: 5 },
  { parent_id: 0, parent_code: 'basic', perm_name: '不良分类', perm_code: 'basic:defect', type: 'menu', icon: 'AlertOutlined', path: '/basic/defects', sort_order: 6 },
  { parent_id: 0, parent_code: 'basic', perm_name: '编码管理', perm_code: 'basic:number-rule', type: 'menu', icon: 'KeyOutlined', path: '/basic/number-rules', sort_order: 7 },
  // 生产管理
  { parent_id: 0, perm_name: '生产管理', perm_code: 'production', type: 'menu', icon: 'ToolOutlined', path: 'production', sort_order: 1 },
  { parent_id: 0, parent_code: 'production', perm_name: '生产订单', perm_code: 'production:order', type: 'menu', icon: 'FileTextOutlined', path: '/production/orders', sort_order: 1 },
  { parent_id: 0, parent_code: 'production', perm_name: '生产报工', perm_code: 'production:reporting', type: 'menu', icon: 'ProfileOutlined', path: '/production/reporting', sort_order: 2 },
  // 质量管理
  { parent_id: 0, perm_name: '质量管理', perm_code: 'quality', type: 'menu', icon: 'ExperimentOutlined', path: 'quality', sort_order: 2 },
  { parent_id: 0, parent_code: 'quality', perm_name: '检验标准', perm_code: 'quality:standard', type: 'menu', icon: 'SafetyCertificateOutlined', path: '/quality/standards', sort_order: 8 },
  { parent_id: 0, parent_code: 'quality', perm_name: '来料检验', perm_code: 'quality:incoming', type: 'menu', icon: 'ExperimentOutlined', path: '/quality/incoming', sort_order: 1 },
  { parent_id: 0, parent_code: 'quality', perm_name: '产品检测', perm_code: 'quality:product', type: 'menu', icon: 'ExperimentOutlined', path: '/quality/product', sort_order: 2 },
  { parent_id: 0, parent_code: 'quality', perm_name: '微生物检验', perm_code: 'quality:microbe', type: 'menu', icon: 'ExperimentOutlined', path: '/quality/microbe', sort_order: 3 },
  { parent_id: 0, parent_code: 'quality', perm_name: '环境检验', perm_code: 'quality:environment', type: 'menu', icon: 'ExperimentOutlined', path: '/quality/environment', sort_order: 4 },
  { parent_id: 0, parent_code: 'quality', perm_name: '投诉管理', perm_code: 'quality:complaint', type: 'menu', icon: 'BellOutlined', path: '/quality/complaints', sort_order: 5 },
  { parent_id: 0, parent_code: 'quality:complaint', perm_name: '客诉管理', perm_code: 'quality:complaint:customer', type: 'menu', icon: 'BellOutlined', path: '/quality/complaints', sort_order: 1 },
  { parent_id: 0, parent_code: 'quality:complaint', perm_name: '供应商投诉', perm_code: 'quality:complaint:supplier', type: 'menu', icon: 'TeamOutlined', path: '/quality/supplier', sort_order: 2 },
  { parent_id: 0, parent_code: 'quality', perm_name: '仪器管理', perm_code: 'quality:instrument', type: 'menu', icon: 'ToolOutlined', path: '/quality/instruments', sort_order: 6 },
  // 设备管理
  { parent_id: 0, perm_name: '设备管理', perm_code: 'device', type: 'menu', icon: 'ToolOutlined', path: 'device', sort_order: 3 },
  { parent_id: 0, parent_code: 'device', perm_name: '设备档案', perm_code: 'device:list', type: 'menu', icon: 'ToolOutlined', path: '/device/list', sort_order: 1 },
  { parent_id: 0, parent_code: 'device', perm_name: '保养标准', perm_code: 'device:maintenance-standard', type: 'menu', icon: 'ProfileOutlined', path: '/device/maintenance-standard', sort_order: 2 },
  { parent_id: 0, parent_code: 'device', perm_name: '保养管理', perm_code: 'device:maintenance', type: 'menu', icon: 'ToolOutlined', path: '/device/maintenance', sort_order: 3 },
  { parent_id: 0, parent_code: 'device', perm_name: '保养矩阵', perm_code: 'device:maintenance-matrix', type: 'menu', icon: 'AppstoreOutlined', path: '/device/maintenance/matrix', sort_order: 4 },
  { parent_id: 0, parent_code: 'device', perm_name: '设备OEE', perm_code: 'device:oee', type: 'menu', icon: 'LineChartOutlined', path: '/device/oee', sort_order: 5 },
  { parent_id: 0, parent_code: 'device', perm_name: '设备看板', perm_code: 'device:dashboard', type: 'menu', icon: 'DashboardOutlined', path: '/device/dashboard', sort_order: 6 },
  { parent_id: 0, parent_code: 'device', perm_name: '故障管理', perm_code: 'device:fault', type: 'menu', icon: 'WarningOutlined', path: '/device/fault', sort_order: 7 },
  { parent_id: 0, parent_code: 'device', perm_name: '备件管理', perm_code: 'device:spare-part', type: 'menu', icon: 'InboxOutlined', path: '/device/spare-parts', sort_order: 8 },
  { parent_id: 0, parent_code: 'device', perm_name: '校准管理', perm_code: 'device:calibration', type: 'menu', icon: 'AimOutlined', path: '/device/calibration', sort_order: 9 },
  { parent_id: 0, parent_code: 'device', perm_name: '电子档案', perm_code: 'device:document', type: 'menu', icon: 'FolderOutlined', path: '/device/documents', sort_order: 10 },
  { parent_id: 0, parent_code: 'device', perm_name: '历史保养记录', perm_code: 'device:maintenance-history', type: 'menu', icon: 'HistoryOutlined', path: '/device/maintenance-history', sort_order: 11 },
  // 报表中心
  { parent_id: 0, perm_name: '报表中心', perm_code: 'report', type: 'menu', icon: 'PieChartOutlined', path: 'report', sort_order: 5 },
  { parent_id: 0, parent_code: 'report', perm_name: '生产日报', perm_code: 'report:daily', type: 'menu', icon: 'CalendarOutlined', path: '/report/daily', sort_order: 1 },
  { parent_id: 0, parent_code: 'report', perm_name: '质量月报', perm_code: 'report:monthly', type: 'menu', icon: 'FileTextOutlined', path: '/report/monthly', sort_order: 2 },
  { parent_id: 0, parent_code: 'report', perm_name: '效率分析', perm_code: 'report:efficiency', type: 'menu', icon: 'RiseOutlined', path: '/report/efficiency', sort_order: 3 },
  { parent_id: 0, parent_code: 'report', perm_name: '生产报表', perm_code: 'report:production', type: 'menu', icon: 'FileTextOutlined', path: '/report/production', sort_order: 4 },
  { parent_id: 0, parent_code: 'report', perm_name: '质量报表', perm_code: 'report:quality', type: 'menu', icon: 'ExperimentOutlined', path: '/report/quality', sort_order: 5 },
  { parent_id: 0, parent_code: 'report', perm_name: '异常分析', perm_code: 'report:exception', type: 'menu', icon: 'BellOutlined', path: '/report/exception', sort_order: 6 },
  // 自动任务
  { parent_id: 0, perm_name: '自动任务', perm_code: 'auto', type: 'menu', icon: 'ControlOutlined', path: 'auto', sort_order: 6 },
  { parent_id: 0, parent_code: 'auto', perm_name: '任务设置', perm_code: 'auto:task-setting', type: 'menu', icon: 'SettingOutlined', path: '/auto/task-settings', sort_order: 1 },
  { parent_id: 0, parent_code: 'auto', perm_name: '定时任务', perm_code: 'auto:scheduled-task', type: 'menu', icon: 'CalendarOutlined', path: '/auto/scheduled-tasks', sort_order: 2 },
  { parent_id: 0, parent_code: 'auto', perm_name: '任务日志', perm_code: 'auto:task-log', type: 'menu', icon: 'ClockCircleOutlined', path: '/auto/task-logs', sort_order: 3 },
  // 数据大屏
  { parent_id: 0, perm_name: '数据大屏', perm_code: 'bigscreen', type: 'menu', icon: 'DesktopOutlined', path: 'bigscreen', sort_order: 7 },
  { parent_id: 0, parent_code: 'bigscreen', perm_name: '生产实时看板', perm_code: 'bigscreen:production', type: 'menu', icon: 'BarChartOutlined', path: '/bigscreen/production', sort_order: 1 },
  { parent_id: 0, parent_code: 'bigscreen', perm_name: '质量分析看板', perm_code: 'bigscreen:quality', type: 'menu', icon: 'ExperimentOutlined', path: '/bigscreen/quality', sort_order: 2 },
  { parent_id: 0, parent_code: 'bigscreen', perm_name: '管理驾驶舱', perm_code: 'bigscreen:management', type: 'menu', icon: 'PieChartOutlined', path: '/bigscreen/management', sort_order: 3 },
  { parent_id: 0, parent_code: 'bigscreen', perm_name: '环境看板', perm_code: 'bigscreen:environment', type: 'menu', icon: 'EnvironmentOutlined', path: '/bigscreen/environment', sort_order: 4 },
  { parent_id: 0, parent_code: 'bigscreen', perm_name: '能源管理看板', perm_code: 'bigscreen:energy', type: 'menu', icon: 'ThunderboltOutlined', path: '/bigscreen/energy', sort_order: 5 },
  // 报表中心
  { parent_id: 0, perm_name: '报表中心', perm_code: 'report', type: 'menu', icon: 'PieChartOutlined', path: 'report', sort_order: 5 },
  { parent_id: 0, parent_code: 'report', perm_name: '生产日报', perm_code: 'report:daily', type: 'menu', icon: 'CalendarOutlined', path: '/report/daily', sort_order: 1 },
  { parent_id: 0, parent_code: 'report', perm_name: '质量月报', perm_code: 'report:monthly', type: 'menu', icon: 'FileTextOutlined', path: '/report/monthly', sort_order: 2 },
  { parent_id: 0, parent_code: 'report', perm_name: '效率分析', perm_code: 'report:efficiency', type: 'menu', icon: 'RiseOutlined', path: '/report/efficiency', sort_order: 3 },
  { parent_id: 0, parent_code: 'report', perm_name: '生产报表', perm_code: 'report:production', type: 'menu', icon: 'FileTextOutlined', path: '/report/production', sort_order: 4 },
  { parent_id: 0, parent_code: 'report', perm_name: '质量报表', perm_code: 'report:quality', type: 'menu', icon: 'ExperimentOutlined', path: '/report/quality', sort_order: 5 },
  { parent_id: 0, parent_code: 'report', perm_name: '异常分析', perm_code: 'report:exception', type: 'menu', icon: 'BellOutlined', path: '/report/exception', sort_order: 6 },
  // ===== 按钮级权限（type: button）=====
  // 系统管理 - 角色权限
  { parent_id: 0, parent_code: 'system:role', perm_name: '分配权限', perm_code: 'system:role:assign', type: 'button', sort_order: 1 },
  // 生产管理 - 生产订单
  { parent_id: 0, parent_code: 'production:order', perm_name: '订单下发', perm_code: 'production:order:release', type: 'button', sort_order: 1 },
  { parent_id: 0, parent_code: 'production:order', perm_name: '订单关闭', perm_code: 'production:order:close', type: 'button', sort_order: 2 },
  { parent_id: 0, parent_code: 'production:order', perm_name: '新增订单', perm_code: 'production:order:create', type: 'button', sort_order: 3 },
  { parent_id: 0, parent_code: 'production:order', perm_name: '编辑订单', perm_code: 'production:order:update', type: 'button', sort_order: 4 },
  { parent_id: 0, parent_code: 'production:order', perm_name: '删除订单', perm_code: 'production:order:delete', type: 'button', sort_order: 5 },
  // 生产管理 - 生产报工
  { parent_id: 0, parent_code: 'production:reporting', perm_name: '新增报工', perm_code: 'production:reporting:create', type: 'button', sort_order: 1 },
  { parent_id: 0, parent_code: 'production:reporting', perm_name: '报工完工', perm_code: 'production:reporting:finish', type: 'button', sort_order: 2 },
  { parent_id: 0, parent_code: 'production:reporting', perm_name: '报工关闭', perm_code: 'production:reporting:close', type: 'button', sort_order: 3 },
  { parent_id: 0, parent_code: 'production:reporting', perm_name: '编辑报工', perm_code: 'production:reporting:update', type: 'button', sort_order: 4 },
  { parent_id: 0, parent_code: 'production:reporting', perm_name: '删除报工', perm_code: 'production:reporting:delete', type: 'button', sort_order: 5 },
  // 基础数据 - 产线档案
  { parent_id: 0, parent_code: 'basic:line', perm_name: '新增产线', perm_code: 'basic:line:create', type: 'button', sort_order: 1 },
  { parent_id: 0, parent_code: 'basic:line', perm_name: '编辑产线', perm_code: 'basic:line:update', type: 'button', sort_order: 2 },
  { parent_id: 0, parent_code: 'basic:line', perm_name: '删除产线', perm_code: 'basic:line:delete', type: 'button', sort_order: 3 },
  // 基础数据 - 工序档案
  { parent_id: 0, parent_code: 'basic:process', perm_name: '新增工序', perm_code: 'basic:process:create', type: 'button', sort_order: 1 },
  { parent_id: 0, parent_code: 'basic:process', perm_name: '编辑工序', perm_code: 'basic:process:update', type: 'button', sort_order: 2 },
  { parent_id: 0, parent_code: 'basic:process', perm_name: '删除工序', perm_code: 'basic:process:delete', type: 'button', sort_order: 3 },
  // 基础数据 - 设备档案
  { parent_id: 0, parent_code: 'device:list', perm_name: '新增设备', perm_code: 'device:list:create', type: 'button', sort_order: 1 },
  { parent_id: 0, parent_code: 'device:list', perm_name: '编辑设备', perm_code: 'device:list:update', type: 'button', sort_order: 2 },
  { parent_id: 0, parent_code: 'device:list', perm_name: '删除设备', perm_code: 'device:list:delete', type: 'button', sort_order: 3 },
  // 质量管理 - 检验标准
  { parent_id: 0, parent_code: 'quality:standard', perm_name: '复制标准', perm_code: 'quality:standard:copy', type: 'button', icon: 'CopyOutlined', sort_order: 1 },
  { parent_id: 0, parent_code: 'quality:standard', perm_name: '改版标准', perm_code: 'quality:standard:revise', type: 'button', icon: 'BranchesOutlined', sort_order: 2 },
]
